name: test

on:
    # pull_request:
    #     branches:
    #         - main
    workflow_dispatch:

jobs:
    build-test-images:
        name: Build Image for Testing
        runs-on: ubuntu-latest

        permissions:
            packages: write

        steps:
            -
                uses: actions/checkout@v3

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -
                name: Login to ghcr.io registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -
                name: Build unit test docker image and push to GHCR
                uses: docker/build-push-action@v5
                with:
                    push: true
                    context: ./
                    file: ./Dockerfile.unit_test
                    tags: ghcr.io/${{ github.repository }}_unit_test:${{ github.run_id }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    platforms: linux/amd64

    unit-tests:
        runs-on: ubuntu-latest
        needs: [build-test-images]

        permissions:
            packages: read

        steps:
            -
                uses: actions/checkout@v3

            -
                name: Login to ghcr.io registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -
                name: Run unit tests
                run: docker run --rm ghcr.io/${{ github.repository }}_unit_test:"$GITHUB_RUN_ID"
