on:
    workflow_run: 
        workflows: test
        types: completed
    workflow_dispatch:

jobs:
    create-release-version:
        name: Create release version
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: write
            pull-requests: write

        steps:
            -   
                name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   
                name: Build Changelog
                id: github_release
                uses: mikepenz/release-changelog-builder-action@v3
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   
                name: Bump version and push tag
                id: tag_version
                uses: mathieudutour/github-tag-action@v6.1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}

            -   
                name: Create a GitHub release
                id: create_release
                uses: ncipollo/release-action@v1
                with:
                    tag: ${{ steps.tag_version.outputs.new_tag }}
                    name: Release ${{ steps.tag_version.outputs.new_tag }}
                    body: ${{ steps.github_release.outputs.changelog }}

            - 
                name: Repository Dispatch
                uses: peter-evans/repository-dispatch@v2
                with:
                    event-type: on-new-version
                    client-payload: '{ version: "${{ steps.tag_version.outputs.new_tag }}" }'

            - 
                name: Add new tag to the GITHUB_ENV variable
                if: ${{steps.create_release.outcome}} == success
                run: echo ${{steps.tag_version.outputs.new_tag}} >> $GITHUB_ENV
